// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ8BcVF-OjadRs_sxB_3XIs5TsOn-M01k',
    appId: '1:561615127876:web:476ab66341662e20c18311',
    messagingSenderId: '561615127876',
    projectId: 'expense-tracker-22ef6',
    authDomain: 'expense-tracker-22ef6.firebaseapp.com',
    storageBucket: 'expense-tracker-22ef6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9HGybdDBNQobcG5xJ8UgGbAvRYY2FLw',
    appId: '1:561615127876:android:888738899c8bf2fcc18311',
    messagingSenderId: '561615127876',
    projectId: 'expense-tracker-22ef6',
    storageBucket: 'expense-tracker-22ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgT5tCGr6N_njELr4JOZ0aH_J8Ak6Gct8',
    appId: '1:561615127876:ios:18405f6397796cc7c18311',
    messagingSenderId: '561615127876',
    projectId: 'expense-tracker-22ef6',
    storageBucket: 'expense-tracker-22ef6.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
